# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Local Average Kernel Smoothing Method Using A Gaussian Kernel Function
#'
#' @title Local Average Kernel Smoothing Method Using A Gaussian Kernel Function
#' @name laks
#'
#' @param date A \code{numeric} vector containing dates for the smoothing.
#' @param median A \code{numeric} vector contaning measurements for the relevant dates. Can contain NA-values, which will be removed if present.
#' @param bandwidth A \code{double}. The bandwidth used in the kernel smoothing
#' @param average A \code{double} representing the sample mean of relevant measurements. If set to below \code{0}, it will be calculated in this function instead.
#' @param standard_deviation A \code{double} representing the sample standard deviation of relevant measurements. If set to below \code{0}, it will be calculated in this function instead.
#' @param approximate A \code{logical} value. If set to \code{TRUE}, gradients are estimated via second differences. If set to \code{FALSE}, a plug-in estimator of the gradients is used.
#'
#' @description Local average kernel smoothing of a set of measure values
#'
#' @details Measurement values with weight < 0.01 is not included for efficiency
#'
#' @return A \code{list} containing kernel smoothed values.
#'
#' @examples \dontrun{
#'
#'   print(1)
#'
#' }
NULL

#' Local Average Kernel Smoothing Leave One Out Cross Validation
#'
#' @title Local Average Kernel Smoothing Leave One Out Cross Validation
#' @name laks_loo
#'
#' @param date A \code{numeric} vector containing dates for the smoothing.
#' @param median A \code{numeric} vector contaning measurements for the relevant dates. Cannot contain NA-values.
#' @param bandwidth A \code{double}. The bandwidth used in the kernel smoothing
#'
#' @description Local average kernel smoothing loo cv of a set of measure values
#'
#' @details Measurement values with weight < 0.01 is not included for efficiency
#'
#' @return A \code{double}, which is the cross-validation value for the fit given the \code{bandwidth}.
#'
#' @examples \dontrun{
#'
#'   print(1)
#'
#' }
NULL

laks <- function(date, median, bandwidth, average = -0.00001, standard_deviation = -0.00001, approximate = FALSE) {
    .Call(`_nopam_smoothing_laks`, date, median, bandwidth, average, standard_deviation, approximate)
}

laks_loo <- function(date, median, bandwidth) {
    .Call(`_nopam_smoothing_laks_loo`, date, median, bandwidth)
}

#' Local Linear Kernel Smoothing Method Using A Gaussian Kernel Function
#'
#' @title Local Linear Kernel Smoothing Method Using A Gaussian Kernel Function
#' @name llks
#'
#' @param date A \code{numeric} vector containing dates for the smoothing.
#' @param median A \code{numeric} vector contaning measurements for the relevant dates. Can contain NA-values, which will be removed if present.
#' @param bandwidth A \code{double}. The bandwidth used in the kernel smoothing
#' @param average A \code{double} representing the sample mean of relevant measurements. If set to below \code{0}, it will be calculated in this function instead.
#' @param standard_deviation A \code{double} representing the sample standard deviation of relevant measurements. If set to below \code{0}, it will be calculated in this function instead.
#' @param approximate A \code{logical} value. If set to \code{TRUE}, gradients are estimated via second differences. If set to \code{FALSE}, a plug-in estimator of the gradients is used.
#' @param matrix_approach A \code{loigcal} value. Should matrix calculus be used to smooth. Only relevant if \code{method} is \code{ll}. Matrix calculus is faster, but may not be stable in some cases.
#'
#' @description Local linear kernel smoothing of a set of measure values
#'
#' @details Measurement values with weight < 0.01 is not included for efficiency
#'
#' @return A \code{list} containing kernel smoothed values.
#'
#' @examples \dontrun{
#'
#'   print(1)
#'
#' }
NULL

llks <- function(date, median, bandwidth = 11, average = -0.00001, standard_deviation = -0.00001, approximate = FALSE, matrix_approach = TRUE) {
    .Call(`_nopam_smoothing_llks`, date, median, bandwidth, average, standard_deviation, approximate, matrix_approach)
}

#' Moving Median Smoothing Method
#'
#' @title Moving Median Smoothing Method
#' @name moving_median
#'
#' @param date A \code{numeric} vector containing dates for the smoothing.
#' @param median A \code{numeric} vector contaning measurements for the relevant dates. Can contain NA-values, which will be removed if present.
#' @param bandwidth A \code{double}. The bandwidth used in the kernel smoothing
#'
#' @description Moving median smoothing of a set of measure values
#'
#' @details No details.
#'
#' @return A \code{list} containing moving median smoothed values.
#'
#' @examples \dontrun{
#'
#'   print(1)
#'
#' }
NULL

moving_median <- function(date, median, bandwidth = 30L) {
    .Call(`_nopam_smoothing_moving_median`, date, median, bandwidth)
}

rcpparma_hello_world <- function() {
    .Call(`_nopam_smoothing_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_nopam_smoothing_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_nopam_smoothing_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_nopam_smoothing_rcpparma_bothproducts`, x)
}

#' Reduce Bias Type Warnings
#'
#' @title Reduce Bias Type Warnings
#' @name reduce_bias_warnings
#'
#' @param warnings A \code{logical} vector containing raw bias type warnings.
#' @param snooze A \code{integer}. How many days should be used in snoozing.
#'
#' @description Reduce bias type warnings using the snoozing functionality
#'
#' @details No details.
#'
#' @return A \code{logical} vector containing a reduced set of warnings after snoozing.
#'
#' @examples \dontrun{
#'
#'   print(1)
#'
#' }
NULL

reduce_bias_warnings <- function(warnings, snooze = 5L) {
    .Call(`_nopam_smoothing_reduce_bias_warnings`, warnings, snooze)
}

#' Reduce Slope Type Warnings
#'
#' @title Reduce Slope Type Warnings
#' @name reduce_slope_warnings
#'
#' @param data A \code{list} containing slope warning data.
#' @param stringent A \code{logical} value. Should slope warnings be reduced?
#'
#' @description Reduce slope type warnings using the slope functionality
#'
#' @details No details.
#'
#' @return A \code{list} with updated warnings
#'
#' @examples \dontrun{
#'
#'   print(1)
#'
#' }
NULL

reduce_slope_warnings <- function(data, stringent = TRUE) {
    .Call(`_nopam_smoothing_reduce_slope_warnings`, data, stringent)
}

